-- Tecnica Smartworks - catalogo inicial de tareas
-- min_days: plazos minimos en dias (editables desde Administracion).

insert into public.task_types (position, name, description, needs, delivers, min_days, is_discovery) values
(0,  'No sé qué necesito',
     'Técnica analiza el proyecto y define qué tareas técnicas hacen falta.',
     'Briefing, proposal, fecha y venue si hay.',
     'Lista de tareas técnicas del proyecto.', 3, true),
(1,  'Evaluar o elegir venue por posibilidades técnicas',
     'Análisis técnico de venues candidatos.',
     'Venues candidatos, formato, aforo.',
     'Comparativa y recomendación.', 5, false),
(2,  'Visita técnica al venue',
     'Visita presencial para relevar condiciones técnicas.',
     'Venue, contacto, fecha posible.',
     'Informe de visita con fotos.', 7, false),
(3,  'Toma de medidas',
     'Medición en sitio de los espacios indicados.',
     'Venue, qué medir.',
     'Medidas y plano acotado.', 5, false),
(4,  'Desarrollar propuesta técnica',
     'Diseño de la solución técnica para el evento.',
     'Briefing, proposal, presupuesto objetivo.',
     'Propuesta técnica.', 10, false),
(5,  'Sugerir o revisar una propuesta existente',
     'Revisión técnica de una propuesta ya armada.',
     'La propuesta.',
     'Observaciones y alternativas.', 3, false),
(6,  'Overlay sobre el plano de rigging del venue',
     'Superposición del diseño sobre los puntos de rigging del venue.',
     'Plano de rigging, diseño o render.',
     'Plano con overlay y cargas.', 3, false),
(7,  'Documento de requirements para el proveedor',
     'Documento técnico para pedir cotización a proveedores.',
     'Propuesta aprobada, planos.',
     'Request listo para enviar.', 5, false),
(8,  'Conseguir presupuestos',
     'Gestión de cotizaciones con proveedores.',
     'Request, proveedores posibles.',
     'Cotizaciones comparables.', 10, false),
(9,  'Comparar y recomendar proveedor',
     'Análisis de cotizaciones recibidas.',
     'Cotizaciones.',
     'Comparativa y recomendación.', 3, false),
(10, 'Escaletas (show, show call, ensayos, rundown de montaje técnico)',
     'Escaleta técnica del tipo indicado.',
     'Agenda, contenidos, horarios de venue.',
     'La escaleta pedida.', 5, false),
(11, 'Specs de contenidos por superficie',
     'Pixel map, resolución, relación de aspecto y formato por superficie.',
     'Datos del proveedor, planos.',
     'Ficha de specs para diseño y cliente.', 3, false),
(12, 'Validación técnica de contenidos antes de montaje',
     'Chequeo de archivos finales contra specs.',
     'Archivos finales, specs.',
     'Validación por pieza con fecha.', 2, false);
